name: Run Tests

on:
  push:
    branches:
      - main
      # - release/*
      # - feature/*

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      VITE_BOOKING_LOCALHOST: "true" # This is so we can test the booking functionality regardless of feature flag
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Chromium Browser
        run: npx playwright install --with-deps chromium

      - name: Setup LocalHost
        run: |
          nohup pnpm run dev &
          npx wait-on http://localhost:5173

      - name: Run Playwright tests
        run: npx playwright test --project=chromium
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
